//
// Copyright (c) 2016 Vinodh Kumar M. <GreenHex@gmail.com>
//

#include <pebble.h>

// #define DEBUG

#define OUTLINE_LAYER_WIDTH ( PBL_DISPLAY_WIDTH - 6 ) 
#define OUTLINE_LAYER_HEIGHT OUTLINE_LAYER_WIDTH 
#define OUTLINE_LAYER_POS_X ( PBL_DISPLAY_WIDTH / 2 - OUTLINE_LAYER_WIDTH / 2 )
#define OUTLINE_LAYER_POS_Y ( PBL_DISPLAY_HEIGHT / 2 - OUTLINE_LAYER_HEIGHT / 2 )
#define OUTLINE_RECT_FRAME ( GRect( OUTLINE_LAYER_POS_X, OUTLINE_LAYER_POS_Y, OUTLINE_LAYER_WIDTH, OUTLINE_LAYER_HEIGHT ) )

#define SECONDS_LAYER_WIDTH ( OUTLINE_LAYER_WIDTH - 6 )
#define SECONDS_LAYER_HEIGHT SECONDS_LAYER_WIDTH
#define SECONDS_LAYER_POS_X ( OUTLINE_LAYER_WIDTH / 2 - SECONDS_LAYER_WIDTH / 2 )
#define SECONDS_LAYER_POS_Y ( OUTLINE_LAYER_HEIGHT / 2 - SECONDS_LAYER_HEIGHT / 2 )
#define SECONDS_RECT_FRAME ( GRect( SECONDS_LAYER_POS_X, SECONDS_LAYER_POS_Y, SECONDS_LAYER_WIDTH, SECONDS_LAYER_HEIGHT ) )

#define SECONDS_HAND_LENGTH ( SECONDS_LAYER_WIDTH / 2 - 8 )
#define SECONDS_HAND_TAIL_LENGTH 20
#define SECONDS_HAND_THK 1
#define SECONDS_HUB_RADIUS 3

#define MINUTES_LAYER_WIDTH ( 51 )
#define MINUTES_LAYER_HEIGHT MINUTES_LAYER_WIDTH
#define MINUTES_LAYER_POS_X ( OUTLINE_LAYER_WIDTH / 2 - MINUTES_LAYER_WIDTH / 2 )
#define MINUTES_LAYER_POS_Y ( OUTLINE_LAYER_HEIGHT / 4 - MINUTES_LAYER_HEIGHT / 2 + 4 )
#define MINUTES_RECT_FRAME ( GRect( MINUTES_LAYER_POS_X, MINUTES_LAYER_POS_Y, MINUTES_LAYER_WIDTH, MINUTES_LAYER_HEIGHT ) )

#define MINUTES_HAND_LENGTH ( MINUTES_LAYER_WIDTH / 2 - 7 )
#define MINUTES_HAND_TAIL_LENGTH 10
#define MINUTES_HAND_THK 1
#define MINUTES_HUB_RADIUS 3

#define LABEL_WIDTH 70 /* ( PBL_DISPLAY_WIDTH / 2 ) */
#define LABEL_HEIGHT 18 /* ( ( PBL_DISPLAY_HEIGHT - PBL_DISPLAY_WIDTH ) / 2 ) */
// #define LABEL_SIZE ( GSize( LABEL_WIDTH, LABEL_HEIGHT ) )
#define LABEL_TOP_LEFT_RECT ( GRect( 0, 0, LABEL_WIDTH, LABEL_HEIGHT ) )
#define LABEL_TOP_RIGHT_RECT ( GRect( PBL_DISPLAY_WIDTH - LABEL_WIDTH, 0, LABEL_WIDTH, LABEL_HEIGHT ) )
#define LABEL_BOTTOM_RIGHT_RECT ( GRect( PBL_DISPLAY_WIDTH - LABEL_WIDTH, PBL_DISPLAY_HEIGHT - LABEL_HEIGHT, LABEL_WIDTH, LABEL_HEIGHT ) )

Layer *seconds_layer;
